import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import { Navbar } from "@/components/nav";
import { Cursor, CustomCursor } from "@/components/ui/cursor";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden font-sans bg-colorLight`}
      >
        <Cursor/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
