import { Montserrat } from "next/font/google";
import "./globals.css"; 
import { Cursor } from "@/components/ui/cursor";
import Header from '@/components/Header'
  
const montserrat = Montserrat({
  subsets: ['latin'], 
  weight: ['200', '400', '700'],  
  variable: '--font-montserrat',  
});

export const metadata = {
  title: "Symliq",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body
        className={`${montserrat.variable} antialiased overflow-x-hidden   bg-colorLight`}
      >
        <Cursor/> 
        <Header/>
        {children}
      </body>
    </html>
  );
}
