import { Montserrat } from "next/font/google";
import "./globals.css"; 
// import { Navbar } from "@/components/nav";
import { Cursor } from "@/components/ui/cursor";
import Header from '@/components/Header'
 
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const montserrat = Montserrat({
  subsets: ['latin'], // Supports Latin characters
  weight: ['300', '500', '700'], // Choose the weights you need
  variable: '--font-nunito', // Optional: Use a CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body
        className={`${montserrat.variable} antialiased overflow-x-hidden   bg-colorLight`}
      >
        <Cursor/>
        {/* <Navbar/> */}
        <Header/>
        {children}
      </body>
    </html>
  );
}
